# Generated by Django 5.0.6 on 2024-07-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('ruta_img', models.TextField()),
            ],
        ),
    ]
