# Generated by Django 5.0.6 on 2024-07-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0002_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='ruta_img',
            new_name='url_img',
        ),
        migrations.AddField(
            model_name='servicio',
            name='contenido_lista',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
