# Generated by Django 5.0.6 on 2024-07-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0003_rename_ruta_img_servicio_url_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
