# Generated by Django 5.0.6 on 2024-07-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0005_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
